global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alert rules configuration
# Path: /etc/prometheus/alerts.yml jest mountem z ./prometheus/prometheus-alerts.yml (patrz docker-compose.yml)
rule_files:
  - '/etc/prometheus/alerts.yml'

scrape_configs:
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8080']
        labels:
          service: 'gateway'

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8081']
        labels:
          service: 'user-service'

  - job_name: 'report-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['report-service:8082']
        labels:
          service: 'report-service'

  - job_name: 'log-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['log-service:8084']
        labels:
          service: 'log-service'

